[package]
name = "cloudstore"
version = "0.0.1"
authors = ["Graham Wihlidal <graham@wihlidal.ca>"]

[dependencies]
protobuf        = "1.4.3"
futures         = "0.1.18"
futures-cpupool = "0.1.8"
tls-api         = "0.1.14"
grpc            = "0.2.1"

[build-dependencies]
protoc-rust-grpc = "0.2.1"